#.
#Modify CreateNuclear's impact on your terrain
[worldgen]
	#.
	#.
	#Prevents all worldgen added by CreateNuclear from taking effect
	disableWorldGen = false

#.
#Modify rods time and config
[Rods]
	#.
	#.
	#Uranium rod lifespan in reactor
	#20 ticks = 1 second
	#Range: 100 ~ 5000
	"Uranium rod lifespan" = 3600
	#.
	#Graphite rod lifespan in reactor
	#20 ticks = 1 second
	#Range: 100 ~ 5000
	"Graphite rod lifespan" = 3600
	#.
	#Maximum heat a reactor block can handle
	#Avoids reactor failure due to excessive heat
	#Range: 200 ~ 1000
	"Maximum reactor heat" = 1000
	#.
	# Modifying these values may cause imbalances in the reactor
	#Maximum uranium rods per graphite rod
	#Range: 0 ~ 20
	"Uranium max for graphite" = 3
	#.
	# Modifying these values may cause imbalances in the reactor
	#Bonus applied when uranium rods are near each other
	#Range: -20 ~ 20
	"Uranium proxy bonus" = 5
	#.
	# Modifying these values may cause imbalances in the reactor
	#Malus applied when graphite rods are near each other
	#Range: -20 ~ 20
	"Graphite proxy Malus" = -5
	#.
	# Modifying these values may cause imbalances in the reactor
	#Base value of uranium before modifiers
	#Range: -50 ~ 50
	"Base value Uranium" = 25
	#.
	# Modifying these values may cause imbalances in the reactor
	#Base value of graphite before modifiers
	#Range: -50 ~ 50
	"Base value Graphite" = -10

#.
#Explode: ?
["Explosion Reactor"]
	#.
	#.
	#Range: 0.0 ~ 3.4028234663852886E38
	"Size of the reactor explosion" = 10.0
	#.
	#Explanation: 0 = no explosion, 1 = current explosion, 2 = new explosion.
	#Range: 0 ~ 2
	"Type of explosion" = 1
	#.
	#Create Nuclear Explosion Time
	#300 ticks = 15 seconds
	#Range: 100 ~ 1200
	"Duration before exploration" = 600
